name: Publish package
run-name: Publish from ${{ github.ref_type }}/${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  codeartifact:
     uses: ziphycare/ziphy-pipelines/.github/workflows/publish.yml@publish
     with:
        aws_region: us-east-1
        domain: ziphy
        domain_owner: 435048198819
        repository: ziphy
        compact_build_python_versions: '["3.9", "3.11"]'
        compact_build_python_package: false
     secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        gh-pat: ${{ secrets.GH_PAT }}
